# Generated by Django 5.2.17 on 2026-08-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="glasscatalog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="glass_catalog/"),
        ),
    ]
