# Generated by Django 5.2.17 on 2026-08-19 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_glasscatalog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_walkin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("downpayment_pending", "Downpayment Pending Verification"),
                    ("downpayment_verified", "Downpayment Verified"),
                    ("balance_due", "Balance Due"),
                    ("fully_paid", "Fully Paid"),
                ],
                default="unpaid",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("pending_payment", "Pending Payment"),
                    ("confirmed", "Confirmed"),
                    ("cutting", "Cutting"),
                    ("tempering", "Tempering"),
                    ("qc", "QC"),
                    ("ready_dispatch", "Ready for Dispatch"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("on_hold", "On Hold"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("downpayment", "Downpayment (50%)"),
                            ("balance", "Balance Payment"),
                            ("full", "Full Payment"),
                        ],
                        default="downpayment",
                        max_length=20,
                    ),
                ),
                (
                    "amount_claimed",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("proof_image", models.ImageField(upload_to="payment_proofs/")),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=30)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Customer notes e.g. bank name, transaction ref",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount_confirmed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.order",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
